version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_SERVER
      - POSTGRES_DB
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    build: 
      context: ./employee-list
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://127.0.0.1:8000/api/
    ports:
      - "5173:80"
    depends_on:
      - web

volumes:
  postgres_data:
